# version: '3.3'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    # in case of postgres setup :
    # environment:
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_USER: django
    #   POSTGRES_DB: snicc
    ports: 
      - ${HOST_PORT}:8000
    volumes:
      - ./app:/code
    networks:
      - snicc

networks:
  snicc:
